blank_issues_enabled: false
contact_links:
  - name: 🌐 octi suite Website
    url: https://octi-suite.com
    about: Visit our official website
  - name: 📧 Contact & Support
    url: https://octi-design.at
    about: Get in touch with octi design
